version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    assignees:
    - "georgettica"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    assignees:
    - "georgettica"
    schedule:
      interval: "daily"
      
